name: CI

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
      - run: npm install

          
          

          
